export { default as Login } from './login'
export { default as Main } from './main'
export { default as ValidateRegister } from './validate-register'
export { default as Register } from './register'
export { default as PayStubForm } from './pay-stub-form'
